#ifndef METADATA_API_H
#define METADATA_API_H

#include "../../native2/cgocopy_macros.h"

/*
 * Metadata API for CGO integration
 * 
 * These getter functions provide access to the static metadata structs
 * generated by CGOCOPY_STRUCT macros. Static symbols are not visible
 * to Go via CGO, so we need these non-static getter functions.
 */

// Getter functions for struct metadata (implemented in structs.c)
const cgocopy_struct_info* get_SimplePerson_metadata(void);
const cgocopy_struct_info* get_User_metadata(void);
const cgocopy_struct_info* get_Student_metadata(void);
const cgocopy_struct_info* get_Point3D_metadata(void);
const cgocopy_struct_info* get_GameObject_metadata(void);
const cgocopy_struct_info* get_AllTypes_metadata(void);

#endif // METADATA_API_H
